import json
import os

OUTPUT = r"d:\MainProjectMl\ProjectCode\backend\ml\detection_v2\CycloSafe_Detection_Training_V3.ipynb"

def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": [text]}

def code(lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}

cells = [
    md("# CycloSafe - Cyclone Detection Model Training (V3)\n## Objective 1: Binary Classification (Cyclone vs No_Cyclone)\n\n**Dataset:** 5.48 Lakh NASA GIBS Satellite Images\n\n**Architecture:** EfficientNetB0 (Transfer Learning from ImageNet)"),
    
    md("## Step 1: Mount Google Drive and Unzip Dataset"),
    code(["from google.colab import drive\n", "drive.mount('/content/drive')\n"]),
    
    code([
        "import zipfile, os\n",
        "\n",
        "PARTS = [\n",
        "    '/content/drive/MyDrive/dataset_part_1.zip',\n",
        "    '/content/drive/MyDrive/dataset_part_2.zip',\n",
        "    '/content/drive/MyDrive/dataset_part_3.zip',\n",
        "    '/content/drive/MyDrive/dataset_part_4.zip',\n",
        "]\n",
        "EXTRACT_DIR = '/content/dataset_v2'\n",
        "\n",
        "if not os.path.exists(os.path.join(EXTRACT_DIR, 'Cyclone')):\n",
        "    for i, part in enumerate(PARTS, 1):\n",
        "        print(f'Extracting Part {i}/4: {part}...')\n",
        "        with zipfile.ZipFile(part, 'r') as zf:\n",
        "            zf.extractall(EXTRACT_DIR)\n",
        "    print('All parts extracted!')\n",
        "else:\n",
        "    print('Dataset already extracted.')\n",
        "\n",
        "c_count = len(os.listdir(os.path.join(EXTRACT_DIR, 'Cyclone')))\n",
        "nc_count = len(os.listdir(os.path.join(EXTRACT_DIR, 'No_Cyclone')))\n",
        "print(f'Cyclone: {c_count:,} | No_Cyclone: {nc_count:,} | Total: {c_count+nc_count:,}')\n",
    ]),
    
    md("## Step 2: Import Libraries and Set Hyperparameters"),
    code([
        "import numpy as np\n",
        "import tensorflow as tf\n",
        "from tensorflow import keras\n",
        "from tensorflow.keras import layers, models, callbacks, optimizers\n",
        "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
        "import matplotlib.pyplot as plt\n",
        "from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score\n",
        "import seaborn as sns\n",
        "import json, time, shutil, random\n",
        "\n",
        "print(f'TensorFlow: {tf.__version__}')\n",
        "print(f'GPU: {tf.config.list_physical_devices(\"GPU\")}')\n",
        "\n",
        "IMG_SIZE = (224, 224)\n",
        "BATCH_SIZE = 64\n",
        "EPOCHS = 30\n",
        "LEARNING_RATE = 1e-4\n",
        "SEED = 42\n",
    ]),
    
    md("## Step 3: Create Train / Validation / Test Split"),
    code([
        "SPLIT_DIR = '/content/dataset_split'\n",
        "\n",
        "def create_splits(src_dir, split_dir, val_ratio=0.15, test_ratio=0.10):\n",
        "    if os.path.exists(os.path.join(split_dir, 'train', 'Cyclone')):\n",
        "        print('Splits already exist.')\n",
        "        return\n",
        "    for split in ['train', 'val', 'test']:\n",
        "        for cls in ['Cyclone', 'No_Cyclone']:\n",
        "            os.makedirs(os.path.join(split_dir, split, cls), exist_ok=True)\n",
        "    for cls in ['Cyclone', 'No_Cyclone']:\n",
        "        cls_dir = os.path.join(src_dir, cls)\n",
        "        files = [f for f in os.listdir(cls_dir) if f.endswith(('.jpg','.jpeg','.png'))]\n",
        "        random.seed(SEED)\n",
        "        random.shuffle(files)\n",
        "        n = len(files)\n",
        "        n_test = int(n * test_ratio)\n",
        "        n_val = int(n * val_ratio)\n",
        "        n_train = n - n_test - n_val\n",
        "        splits = {'train': files[:n_train], 'val': files[n_train:n_train+n_val], 'test': files[n_train+n_val:]}\n",
        "        for sname, sfiles in splits.items():\n",
        "            dest = os.path.join(split_dir, sname, cls)\n",
        "            for f in sfiles:\n",
        "                os.symlink(os.path.join(cls_dir, f), os.path.join(dest, f))\n",
        "            print(f'  {cls}/{sname}: {len(sfiles):,}')\n",
        "\n",
        "print('Creating splits...')\n",
        "create_splits(EXTRACT_DIR, SPLIT_DIR)\n",
        "\n",
        "for split in ['train', 'val', 'test']:\n",
        "    c = len(os.listdir(os.path.join(SPLIT_DIR, split, 'Cyclone')))\n",
        "    nc = len(os.listdir(os.path.join(SPLIT_DIR, split, 'No_Cyclone')))\n",
        "    print(f'{split.upper()}: {c+nc:,} (Cyclone: {c:,} | No_Cyclone: {nc:,})')\n",
    ]),
    
    md("## Step 4: Build Data Generators with Augmentation"),
    code([
        "train_datagen = ImageDataGenerator(\n",
        "    rescale=1.0/255.0, rotation_range=30, width_shift_range=0.15,\n",
        "    height_shift_range=0.15, shear_range=0.1, zoom_range=0.2,\n",
        "    horizontal_flip=True, vertical_flip=True, brightness_range=[0.8, 1.2],\n",
        "    fill_mode='nearest'\n",
        ")\n",
        "val_test_datagen = ImageDataGenerator(rescale=1.0/255.0)\n",
        "\n",
        "train_gen = train_datagen.flow_from_directory(os.path.join(SPLIT_DIR,'train'), target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', shuffle=True, seed=SEED)\n",
        "val_gen = val_test_datagen.flow_from_directory(os.path.join(SPLIT_DIR,'val'), target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', shuffle=False)\n",
        "test_gen = val_test_datagen.flow_from_directory(os.path.join(SPLIT_DIR,'test'), target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='binary', shuffle=False)\n",
        "\n",
        "print(f'Classes: {train_gen.class_indices}')\n",
        "print(f'Train batches: {len(train_gen)} | Val batches: {len(val_gen)} | Test batches: {len(test_gen)}')\n",
    ]),
    
    md("## Step 5: Visualize Sample Augmented Images"),
    code([
        "batch_imgs, batch_labels = next(train_gen)\n",
        "class_names = list(train_gen.class_indices.keys())\n",
        "fig, axes = plt.subplots(3, 5, figsize=(18, 10))\n",
        "fig.suptitle('Sample Augmented Training Images', fontsize=16, fontweight='bold')\n",
        "for i, ax in enumerate(axes.flat):\n",
        "    if i < len(batch_imgs):\n",
        "        ax.imshow(batch_imgs[i])\n",
        "        label = class_names[int(batch_labels[i])]\n",
        "        ax.set_title(label, color='red' if label=='Cyclone' else 'green', fontweight='bold')\n",
        "    ax.axis('off')\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
    ]),
    
    md("## Step 6: Build EfficientNetB0 Model"),
    code([
        "def build_detection_model(input_shape=(224, 224, 3)):\n",
        "    aug_model = keras.Sequential([\n",
        "        layers.RandomFlip('horizontal_and_vertical'),\n",
        "        layers.RandomRotation(0.15),\n",
        "        layers.RandomZoom(0.1),\n",
        "        layers.RandomContrast(0.1),\n",
        "    ], name='augmentation')\n",
        "    base_model = tf.keras.applications.EfficientNetB0(weights='imagenet', include_top=False, input_shape=input_shape)\n",
        "    base_model.trainable = False\n",
        "    inputs = layers.Input(shape=input_shape, name='satellite_input')\n",
        "    x = aug_model(inputs)\n",
        "    x = base_model(x, training=False)\n",
        "    x = layers.GlobalAveragePooling2D(name='gap')(x)\n",
        "    x = layers.BatchNormalization()(x)\n",
        "    x = layers.Dense(256, activation='relu', name='dense_256')(x)\n",
        "    x = layers.Dropout(0.4, name='dropout_04')(x)\n",
        "    x = layers.Dense(128, activation='relu', name='dense_128')(x)\n",
        "    x = layers.Dropout(0.3, name='dropout_03')(x)\n",
        "    outputs = layers.Dense(1, activation='sigmoid', name='cyclone_probability')(x)\n",
        "    model = models.Model(inputs=inputs, outputs=outputs, name='CycloSafe_Detector_V3')\n",
        "    return model, base_model\n",
        "\n",
        "model, base_model = build_detection_model()\n",
        "model.summary()\n",
    ]),
    
    md("## Step 7: Phase 1 Training - Feature Extraction (Frozen Base)"),
    code([
        "model.compile(optimizer=optimizers.Adam(learning_rate=1e-3), loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.AUC(name='auc')])\n",
        "\n",
        "phase1_callbacks = [\n",
        "    callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True, verbose=1),\n",
        "    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, verbose=1),\n",
        "]\n",
        "\n",
        "print('PHASE 1: Feature Extraction (Base Model Frozen)')\n",
        "t0 = time.time()\n",
        "history_phase1 = model.fit(train_gen, epochs=10, validation_data=val_gen, callbacks=phase1_callbacks, verbose=1)\n",
        "phase1_time = time.time() - t0\n",
        "print(f'Phase 1 completed in {phase1_time/60:.1f} minutes')\n",
    ]),
    
    md("## Step 8: Phase 2 Training - Fine-Tuning (Unfrozen Base)"),
    code([
        "base_model.trainable = True\n",
        "for layer in base_model.layers[:100]:\n",
        "    layer.trainable = False\n",
        "\n",
        "model.compile(optimizer=optimizers.Adam(learning_rate=LEARNING_RATE), loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.AUC(name='auc')])\n",
        "\n",
        "phase2_callbacks = [\n",
        "    callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),\n",
        "    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-7, verbose=1),\n",
        "    callbacks.ModelCheckpoint('/content/best_cyclone_detector.keras', monitor='val_accuracy', save_best_only=True, verbose=1),\n",
        "]\n",
        "\n",
        "print('PHASE 2: Fine-Tuning (Base Model Partially Unfrozen)')\n",
        "t0 = time.time()\n",
        "history_phase2 = model.fit(train_gen, epochs=EPOCHS, validation_data=val_gen, callbacks=phase2_callbacks, verbose=1)\n",
        "phase2_time = time.time() - t0\n",
        "print(f'Phase 2 completed in {phase2_time/60:.1f} minutes')\n",
        "print(f'Total training time: {(phase1_time + phase2_time)/60:.1f} minutes')\n",
    ]),
    
    md("## Step 9: Plot Training History"),
    code([
        "def combine_histories(h1, h2):\n",
        "    combined = {}\n",
        "    for key in h1.history:\n",
        "        combined[key] = h1.history[key] + h2.history[key]\n",
        "    return combined\n",
        "\n",
        "full_history = combine_histories(history_phase1, history_phase2)\n",
        "fig, axes = plt.subplots(1, 3, figsize=(20, 5))\n",
        "fig.suptitle('CycloSafe Detection Model - Training History', fontsize=16, fontweight='bold')\n",
        "for i, (metric, label) in enumerate([('accuracy','Accuracy'),('loss','Loss'),('auc','AUC')]):\n",
        "    axes[i].plot(full_history[metric], label=f'Train {label}', linewidth=2)\n",
        "    axes[i].plot(full_history[f'val_{metric}'], label=f'Val {label}', linewidth=2)\n",
        "    axes[i].set_title(label, fontsize=14)\n",
        "    axes[i].set_xlabel('Epoch')\n",
        "    axes[i].legend()\n",
        "    axes[i].grid(True, alpha=0.3)\n",
        "plt.tight_layout()\n",
        "plt.savefig('/content/training_history.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
    ]),
    
    md("## Step 10: Evaluate on Test Set"),
    code([
        "best_model = keras.models.load_model('/content/best_cyclone_detector.keras')\n",
        "test_loss, test_accuracy, test_auc = best_model.evaluate(test_gen, verbose=1)\n",
        "print(f'Test Accuracy: {test_accuracy*100:.2f}% | Test AUC: {test_auc:.4f}')\n",
        "\n",
        "test_gen.reset()\n",
        "y_pred_prob = best_model.predict(test_gen, verbose=1)\n",
        "y_pred = (y_pred_prob > 0.5).astype(int).flatten()\n",
        "y_true = test_gen.classes\n",
        "class_names = list(test_gen.class_indices.keys())\n",
        "\n",
        "print('\\nCLASSIFICATION REPORT')\n",
        "print(classification_report(y_true, y_pred, target_names=class_names, digits=4))\n",
        "roc_score = roc_auc_score(y_true, y_pred_prob)\n",
        "print(f'ROC-AUC Score: {roc_score:.4f}')\n",
    ]),
    
    md("## Step 11: Confusion Matrix"),
    code([
        "cm = confusion_matrix(y_true, y_pred)\n",
        "fig, ax = plt.subplots(figsize=(8, 6))\n",
        "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names, ax=ax)\n",
        "ax.set_title('Confusion Matrix - CycloSafe Detection V3', fontsize=14, fontweight='bold')\n",
        "ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')\n",
        "plt.tight_layout()\n",
        "plt.savefig('/content/confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "\n",
        "tn, fp, fn, tp = cm.ravel()\n",
        "print(f'TP: {tp:,} | TN: {tn:,} | FP: {fp:,} | FN: {fn:,}')\n",
        "print(f'Precision: {tp/(tp+fp)*100:.2f}% | Recall: {tp/(tp+fn)*100:.2f}% | F1: {2*tp/(2*tp+fp+fn)*100:.2f}%')\n",
    ]),
    
    md("## Step 12: Find Optimal Threshold and Save Config"),
    code([
        "from sklearn.metrics import precision_recall_curve\n",
        "\n",
        "precisions, recalls, thresholds = precision_recall_curve(y_true, y_pred_prob)\n",
        "f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-8)\n",
        "best_idx = np.argmax(f1_scores)\n",
        "best_threshold = float(thresholds[best_idx])\n",
        "print(f'Optimal Threshold: {best_threshold:.6f} | Best F1: {f1_scores[best_idx]:.4f}')\n",
        "\n",
        "config = {'threshold': best_threshold, 'test_accuracy': float(test_accuracy), 'test_auc': float(test_auc), 'roc_auc': float(roc_score), 'class_names': class_names, 'total_training_images': c_count + nc_count, 'model_version': 'V3'}\n",
        "with open('/content/detection_v3_config.json', 'w') as f:\n",
        "    json.dump(config, f, indent=4)\n",
        "print(json.dumps(config, indent=4))\n",
    ]),
    
    md("## Step 13: Save Model to Google Drive"),
    code([
        "SAVE_DIR = '/content/drive/MyDrive/CycloSafe_Models'\n",
        "os.makedirs(SAVE_DIR, exist_ok=True)\n",
        "shutil.copy('/content/best_cyclone_detector.keras', os.path.join(SAVE_DIR, 'cyclone_detector.keras'))\n",
        "shutil.copy('/content/detection_v3_config.json', os.path.join(SAVE_DIR, 'detection_v3_config.json'))\n",
        "shutil.copy('/content/training_history.png', os.path.join(SAVE_DIR, 'training_history.png'))\n",
        "shutil.copy('/content/confusion_matrix.png', os.path.join(SAVE_DIR, 'confusion_matrix.png'))\n",
        "print('MODEL SAVED TO GOOGLE DRIVE!')\n",
        "print(f'Location: {SAVE_DIR}')\n",
    ]),
    
    md("## Step 14: Download Model Directly"),
    code([
        "from google.colab import files\n",
        "files.download('/content/best_cyclone_detector.keras')\n",
        "files.download('/content/detection_v3_config.json')\n",
    ]),
    
    md("---\n## Training Complete!\n\n**Next Steps:**\n1. Download `cyclone_detector.keras` and `detection_v3_config.json` from Google Drive\n2. Place them in `backend/models/`\n3. Restart your backend server\n4. Your dashboard will now use the new V3 model trained on 5.48 Lakh images!\n\n---\n*CycloSafe - AI-Based Tropical Cyclone Monitoring System*"),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(OUTPUT, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook saved to: {OUTPUT}")
print(f"Size: {os.path.getsize(OUTPUT) / 1024:.1f} KB")
